INSERT INTO ProyectoBD.dbo.Materia (Clave,Nombre_Materia,Tipo_Asignatura,Nivel,Semestre,Creditos) VALUES
	 (N'T101',N'PROGRAMACION',N'OBLIGATORIA',1,2,6.0),
	 (N'T102',N'ANALISIS Y DISEÑO DE SISTEMAS',N'OBLIGATORIA',1,1,9.0),
	 (N'T103',N'ESTRUCTURA DE DATOS',N'OBLIGATORIA',1,3,6.0),
	 (N'T104',N'ADMINISTRACCION DE SISTEMAS OPERATIVOS',N'OBLIGATORIA',1,1,6.0),
	 (N'T105',N'DISEÑO DIGITAL',N'OBLIGATORIA',1,4,6.0),
	 (N'T106',N'ARQUITECTURA DE COMPUTADORAS',N'OBLIGATORIA',1,5,7.5),
	 (N'T107',N'FUNDAMENTOS DE FISICA',N'OBLIGATORIA',1,2,6.0),
	 (N'T108',N'ECUACIONES DIFERENCIALES',N'OBLIGATORIA',1,2,9.0),
	 (N'T109',N'PROBABILIDAD',N'OBLIGATORIA',1,3,9.0),
	 (N'T110',N'CALCULO DIFERENCIAL E INTEGRAL',N'OBLIGATORIA',1,1,10.5);
INSERT INTO ProyectoBD.dbo.Materia (Clave,Nombre_Materia,Tipo_Asignatura,Nivel,Semestre,Creditos) VALUES
	 (N'T111',N'VARIABLE COMPLEJA',N'OBLIGATORIA',1,3,6.0),
	 (N'T112',N'ALGEBRA LINEAL',N'OBLIGATORIA',1,1,12.0),
	 (N'T113',N'ELECTROMAGNETISMO',N'OBLIGATORIA',1,4,9.0),
	 (N'T114',N'CALCULO MULTIVARIABLE',N'OBLIGATORIA',1,2,10.5),
	 (N'T115',N'ADMINISTRACION ORGANIZACIONAL',N'OBLIGATORIA',1,2,4.5),
	 (N'T116',N'ETICA, PROFESION Y SOCIEDAD',N'OBLIGATORIA',1,2,4.5),
	 (N'T117',N'COMUNICACION ORAL Y ESCRITA',N'OBLIGATORIA',1,1,6.0),
	 (N'T118',N'INGLES I',N'OBLIGATORIA',1,2,3.0),
	 (N'T119',N'INGLES II',N'OBLIGATORIA',1,3,3.0),
	 (N'T120',N'PROGRAMACION ESTRUCTURADA',N'ELEGIBLE',1,1,7.5);
INSERT INTO ProyectoBD.dbo.Materia (Clave,Nombre_Materia,Tipo_Asignatura,Nivel,Semestre,Creditos) VALUES
	 (N'T121',N'SOCIEDAD, CIENCIA Y TECNOLOGIA',N'ELEGIBLE',1,2,4.5),
	 (N'T201',N'SEÑALES Y SISTEMAS',N'OBLIGATORIA',2,3,7.5),
	 (N'T202',N'PROPAGACION DE ONDAS ELECTROMAGNETICAS',N'OBLIGATORIA',2,5,7.5),
	 (N'T203',N'ELECTRONICA',N'OBLIGATORIA',2,4,7.5),
	 (N'T204',N'TEORIA DE LOS CIRCUITOS',N'OBLIGATORIA',2,3,7.5),
	 (N'T205',N'TEORIA DE LA INFORMACION',N'OBLIGATORIA',2,6,7.5),
	 (N'T206',N'TEORIA DE LAS COMUNICACIONES',N'OBLIGATORIA',2,4,7.5),
	 (N'T207',N'COMUNICACIONES DIGITALES',N'OBLIGATORIA',2,5,7.5),
	 (N'T208',N'PROCESAMIENTO DIGITAL DE SE?ALES',N'OBLIGATORIA',2,5,10.5),
	 (N'T209',N'TELEFONIA',N'OBLIGATORIA',2,6,7.5);
INSERT INTO ProyectoBD.dbo.Materia (Clave,Nombre_Materia,Tipo_Asignatura,Nivel,Semestre,Creditos) VALUES
	 (N'T210',N'SISTEMAS CELULARES',N'OBLIGATORIA',2,7,7.5),
	 (N'T211',N'PROTOCOLOS DE INTERNET',N'OBLIGATORIA',2,6,7.5),
	 (N'T212',N'SISTEMAS DISTRIBUIDOS',N'OBLIGATORIA',2,7,7.5),
	 (N'T213',N'INGENIERIA WEB',N'OBLIGATORIA',2,5,7.5),
	 (N'T214',N'PROGRAMACION AVANZADA',N'OBLIGATORIA',2,4,9.0),
	 (N'T215',N'BASES DE DATOS',N'OBLIGATORIA',2,4,7.5),
	 (N'T216',N'TRANSMISION DE DATOS',N'OBLIGATORIA',2,5,7.5),
	 (N'T217',N'INFORMACION FINANCIERA E INGENIERIA ECONOMICA',N'OBLIGATORIA',2,3,4.5),
	 (N'T219',N'INGLES III',N'OBLIGATORIA',2,4,3.0),
	 (N'T220',N'METODOS NUMERICOS',N'ELEGIBLE',2,3,7.5);
INSERT INTO ProyectoBD.dbo.Materia (Clave,Nombre_Materia,Tipo_Asignatura,Nivel,Semestre,Creditos) VALUES
	 (N'T221',N'ELECTRONICA PARA COMUNICACIONES',N'ELEGIBLE',2,4,7.5),
	 (N'T222',N'OPTICA',N'ELEGIBLE',2,4,7.5),
	 (N'T223',N'DESARROLLO SUSTENTABLE',N'ELEGIBLE',2,2,4.5),
	 (N'T224',N'ECONOMIA PARA INGENIEROS',N'ELEGIBLE',2,3,4.5),
	 (N'T225',N'INGLES IV',N'ELEGIBLE',2,4,3.0),
	 (N'T226',N'REDES INALAMBRICAS',N'OPTATIVA I',2,8,7.5),
	 (N'T227',N'REDES NEURONALES',N'OPTATIVA I',2,8,7.5),
	 (N'T228',N'LOGICA DIFUSA',N'OPTATIVA I',2,8,7.5),
	 (N'T229',N'SISTEMAS DE INFORMACION GEOGRAFICA',N'OPTATIVA I',2,8,7.5),
	 (N'T230',N'PROGRAMACION DE DISPOSITIVOS MOVILES',N'OPTATIVA I',2,8,7.5);
INSERT INTO ProyectoBD.dbo.Materia (Clave,Nombre_Materia,Tipo_Asignatura,Nivel,Semestre,Creditos) VALUES
	 (N'T231',N'NORMATIVIDAD EN TELECOMUNICACIONES E INFORMATICA',N'OPTATIVA I',2,8,7.5),
	 (N'T301',N'REDES INTELIGENTES',N'OBLIGATORIA',3,7,4.5),
	 (N'T302',N'LINEAS DE TRANSMISION Y ANTENAS',N'OBLIGATORIA',2,6,7.5),
	 (N'T303',N'SEGURIDAD EN REDES',N'OBLIGATORIA',3,8,6.0),
	 (N'T304',N'MULTIMEDIA',N'OBLIGATORIA',3,7,6.0),
	 (N'T305',N'BASES DE DATOS DISTRIBUIDAS',N'OBLIGATORIA',3,7,7.5),
	 (N'T306',N'METODOLOGIA DE LA INVESTIGACION',N'OBLIGATORIA',3,8,6.0),
	 (N'T307',N'ADMINISTRACION DE PROYECTOS',N'OBLIGATORIA',3,6,6.0),
	 (N'T308',N'LIDERAZGO Y EMPRENDEDORES',N'OBLIGATORIA',3,7,4.5),
	 (N'T310',N'CRIPTOGRAFIA',N'OPTATIVA II',3,9,7.5);
INSERT INTO ProyectoBD.dbo.Materia (Clave,Nombre_Materia,Tipo_Asignatura,Nivel,Semestre,Creditos) VALUES
	 (N'T311',N'MICROONDAS',N'OPTATIVA II',3,9,7.5),
	 (N'T312',N'PROCESAMIENTO DE IMAGENES',N'OPTATIVA II',3,9,7.5),
	 (N'T313',N'TELEVISION DIGITAL',N'OPTATIVA II',3,9,7.5),
	 (N'T314',N'SISTEMAS DE CALIDAD',N'OPTATIVA II',3,9,7.5),
	 (N'T315',N'PROCESAMIENTO DE VOZ',N'OPTATIVA II',3,9,7.5),
	 (N'T316',N'FILTRADO AVANZADO',N'OPTATIVA II',3,9,7.5),
	 (N'T401',N'PROYECTO TERMINAL I',N'OBLIGATORIA',4,9,7.5),
	 (N'T402',N'PROYECTO TERMINAL II',N'OBLIGATORIA',4,10,7.5),
	 (N'T403',N'REDES DE TELECOMUNICACIONES',N'OBLIGATORIA',4,7,6.0),
	 (N'T404',N'APLICACIONES DISTRIBUIDAS',N'OBLIGATORIA',4,8,6.0);
INSERT INTO ProyectoBD.dbo.Materia (Clave,Nombre_Materia,Tipo_Asignatura,Nivel,Semestre,Creditos) VALUES
	 (N'T405',N'DISPOSITIVOS PROGRAMABLES',N'OBLIGATORIA',4,6,7.5);
